package com.example.easymoji2

object EmojiDatabase {
    val emojis: List<EmojiData> = listOf(
        // Happy emotions
        EmojiData("😊", listOf("smile", "happy", "smiling"), listOf("happy", "joyful", "pleased"), listOf("greeting", "friendly"), "A smiling face with smiling eyes", 
            listOf("yellow face", "smiling eyes", "cheeks", "round")),
        EmojiData("😄", listOf("grin", "laughing", "laugh"), listOf("happy", "joyful", "excited"), listOf("celebration", "success"), "Grinning face with smiling eyes",
            listOf("yellow face", "big smile", "open mouth", "smiling eyes", "teeth")),
        EmojiData("😃", listOf("joy", "happy", "excited"), listOf("happy", "excited", "enthusiastic"), listOf("celebration", "good news"), "Grinning face with big eyes",
            listOf("yellow face", "big eyes", "wide smile", "open mouth", "excited")),
        EmojiData("😁", listOf("beaming", "grin", "smile"), listOf("happy", "cheerful", "delighted"), listOf("success", "achievement"), "Beaming face with smiling eyes",
            listOf("yellow face", "beaming smile", "closed eyes", "cheerful")),
        EmojiData("😆", listOf("laughing", "satisfied", "happy"), listOf("happy", "amused", "cheerful"), listOf("joke", "funny moment"), "Grinning squinting face",
            listOf("yellow face", "squinting eyes", "wide smile", "laughing")),
        
        // Love & Heart
        EmojiData("❤️", listOf("heart", "love", "red heart"), listOf("love", "affection", "caring"), listOf("romance", "appreciation"), "Red heart",
            listOf("red", "solid", "classic", "simple", "red color")),
        EmojiData("💕", listOf("two hearts", "love", "hearts"), listOf("love", "romance", "affection"), listOf("romance", "couple"), "Two hearts",
            listOf("pink", "two", "pink hearts", "pair", "pink color")),
        EmojiData("💖", listOf("sparkling heart", "love"), listOf("love", "adoration", "affection"), listOf("romance", "gift"), "Sparkling heart",
            listOf("pink", "sparkle", "sparkles", "shiny", "glitter", "pink with sparkle", "pink heart with sparkle", "glowing")),
        EmojiData("💗", listOf("growing heart", "love"), listOf("love", "growing affection"), listOf("romance", "new love"), "Growing heart",
            listOf("pink", "growing", "expanding", "pink gradient", "light pink")),
        EmojiData("💓", listOf("beating heart", "love", "heartbeat"), listOf("loving", "excited", "nervous"), listOf("romance", "excitement"), "Beating heart",
            listOf("red", "beating", "pulsing", "animated", "red pulsing")),
        EmojiData("💝", listOf("gift heart", "love", "present"), listOf("loving", "generous", "affectionate"), listOf("romance", "gift"), "Heart with ribbon",
            listOf("pink", "ribbon", "bow", "gift", "pink with ribbon", "pink heart with bow", "wrapped")),
        EmojiData("💘", listOf("cupid", "love", "arrow"), listOf("loving", "romantic", "infatuated"), listOf("romance", "love"), "Heart with arrow",
            listOf("red", "arrow", "cupid", "red heart with arrow", "pierced")),
        EmojiData("💞", listOf("revolving hearts", "love", "hearts"), listOf("loving", "romantic", "affectionate"), listOf("romance", "love"), "Revolving hearts",
            listOf("pink", "revolving", "spinning", "multiple", "pink hearts spinning")),
        EmojiData("💟", listOf("heart decoration", "love", "decoration"), listOf("loving", "decorative", "affectionate"), listOf("decoration", "love"), "Heart decoration",
            listOf("purple", "decorative", "ornament", "purple heart", "decorated")),
        EmojiData("❣️", listOf("heart exclamation", "love", "emphasis"), listOf("loving", "emphatic", "affectionate"), listOf("emphasis", "love"), "Heart exclamation",
            listOf("red", "exclamation", "mark", "red exclamation heart")),
        EmojiData("💔", listOf("broken heart", "sad", "heartbreak"), listOf("sad", "heartbroken", "disappointed"), listOf("heartbreak", "sadness"), "Broken heart",
            listOf("red", "broken", "cracked", "split", "red broken heart", "two pieces")),
        EmojiData("😍", listOf("heart eyes", "love", "adore"), listOf("love", "adoration", "infatuation"), listOf("crush", "attraction"), "Smiling face with heart-eyes",
            listOf("yellow face", "heart eyes", "red hearts", "smiling", "infatuated")),
        
        // Sad emotions
        EmojiData("😢", listOf("cry", "sad", "tears"), listOf("sad", "unhappy", "disappointed"), listOf("loss", "disappointment"), "Crying face",
            listOf("yellow face", "tears", "crying", "blue tears", "sad eyes", "teardrops")),
        EmojiData("😭", listOf("sobbing", "crying", "tears"), listOf("sad", "upset", "distressed"), listOf("loss", "heartbreak"), "Loudly crying face",
            listOf("yellow face", "many tears", "streaming tears", "blue tears", "sobbing", "watery eyes")),
        EmojiData("🤢", listOf("nauseated", "sick", "disgusted"), listOf("sick", "disgusted", "unwell"), listOf("illness", "disgust"), "Nauseated face",
            listOf("green face", "vomiting", "nauseated", "green color", "sick green", "green face vomiting", "green sick face")),
        EmojiData("🤮", listOf("vomiting", "sick", "puke"), listOf("sick", "disgusted", "nauseated"), listOf("illness", "disgust"), "Face vomiting",
            listOf("green face", "vomiting", "puking", "green color", "sick", "green vomiting face")),
        EmojiData("😔", listOf("pensive", "sad", "thoughtful"), listOf("sad", "melancholy", "reflective"), listOf("regret", "disappointment"), "Pensive face",
            listOf("yellow face", "downcast", "sad eyes", "thoughtful", "melancholy")),
        EmojiData("😞", listOf("disappointed", "sad"), listOf("sad", "disappointed", "dejected"), listOf("failure", "disappointment"), "Disappointed face",
            listOf("yellow face", "frowning", "disappointed", "sad mouth")),
        EmojiData("😟", listOf("worried", "concerned"), listOf("worried", "anxious", "concerned"), listOf("problem", "trouble"), "Worried face",
            listOf("yellow face", "worried", "concerned", "furrowed brow")),
        
        // Angry emotions
        EmojiData("😠", listOf("angry", "mad", "annoyed"), listOf("angry", "frustrated", "irritated"), listOf("conflict", "argument"), "Angry face",
            listOf("red face", "angry", "red color", "frowning", "red angry face", "mad red")),
        EmojiData("😡", listOf("rage", "angry", "furious"), listOf("angry", "furious", "enraged"), listOf("conflict", "outrage"), "Pouting face",
            listOf("red face", "very angry", "steam", "red color", "furious red", "red pouting")),
        EmojiData("🤬", listOf("swearing", "angry", "cursing"), listOf("angry", "furious", "outraged"), listOf("conflict", "extreme anger"), "Face with symbols over mouth",
            listOf("yellow face", "symbols", "curse words", "censored", "masked mouth")),
        
        // Surprised emotions
        EmojiData("😲", listOf("astonished", "surprised", "shocked"), listOf("surprised", "shocked", "amazed"), listOf("surprise", "unexpected news"), "Astonished face",
            listOf("yellow face", "wide eyes", "open mouth", "surprised", "shocked")),
        EmojiData("😮", listOf("open mouth", "surprised"), listOf("surprised", "shocked", "amazed"), listOf("surprise", "discovery"), "Face with open mouth",
            listOf("yellow face", "open mouth", "oval mouth", "surprised")),
        EmojiData("😯", listOf("hushed", "surprised"), listOf("surprised", "shocked", "speechless"), listOf("surprise", "unexpected"), "Hushed face",
            listOf("yellow face", "small mouth", "hushed", "quiet")),
        EmojiData("😱", listOf("scream", "fear", "shocked"), listOf("fear", "shocked", "terrified"), listOf("horror", "scary moment"), "Face screaming in fear",
            listOf("yellow face", "screaming", "wide eyes", "open mouth", "terrified", "hands on cheeks")),
        
        // Tired & Sleepy
        EmojiData("😴", listOf("sleep", "tired", "sleepy"), listOf("tired", "sleepy", "exhausted"), listOf("bedtime", "late night"), "Sleeping face",
            listOf("blue face", "sleeping", "zzz", "blue color", "blue sleeping face", "tired blue", "sleep bubbles")),
        EmojiData("😪", listOf("sleepy", "tired"), listOf("tired", "sleepy", "drowsy"), listOf("bedtime", "exhaustion"), "Sleepy face",
            listOf("yellow face", "sleepy", "tear", "tired", "drowsy")),
        EmojiData("😫", listOf("tired", "weary", "exhausted"), listOf("tired", "exhausted", "weary"), listOf("long day", "hard work"), "Tired face",
            listOf("yellow face", "very tired", "exhausted", "weary", "sweat")),
        
        // Cool & Confident
        EmojiData("😎", listOf("cool", "sunglasses", "confident"), listOf("cool", "confident", "relaxed"), listOf("success", "achievement"), "Smiling face with sunglasses",
            listOf("yellow face", "sunglasses", "black glasses", "cool", "shades", "smiling with glasses")),
        EmojiData("🤩", listOf("star struck", "amazed", "impressed"), listOf("amazed", "impressed", "excited"), listOf("celebration", "achievement"), "Star-struck",
            listOf("yellow face", "stars", "sparkles", "star eyes", "glittering eyes", "stars in eyes")),
        EmojiData("😏", listOf("smirk", "confident", "smug"), listOf("confident", "smug", "satisfied"), listOf("success", "victory"), "Smirking face",
            listOf("yellow face", "smirk", "one eye closed", "confident", "sly")),
        
        // Food
        EmojiData("🍕", listOf("pizza", "food"), listOf("hungry", "satisfied"), listOf("meal", "dinner", "party"), "Pizza slice",
            listOf("yellow", "orange", "cheese", "triangle", "slice", "pepperoni", "red toppings")),
        EmojiData("🍔", listOf("burger", "hamburger", "food"), listOf("hungry", "satisfied"), listOf("meal", "fast food"), "Hamburger",
            listOf("brown", "yellow", "bun", "patty", "lettuce", "burger", "sandwich")),
        EmojiData("🍰", listOf("cake", "dessert", "birthday"), listOf("happy", "satisfied"), listOf("birthday", "celebration"), "Shortcake",
            listOf("pink", "white", "cream", "strawberry", "pink cake", "white frosting", "pink with white")),
        EmojiData("🍎", listOf("apple", "fruit", "healthy"), listOf("healthy", "fresh"), listOf("snack", "health"), "Red apple",
            listOf("red", "green leaf", "red apple", "round", "red fruit")),
        EmojiData("☕", listOf("coffee", "drink", "caffeine"), listOf("energetic", "awake"), listOf("morning", "break", "work"), "Hot beverage",
            listOf("brown", "steam", "hot", "cup", "brown coffee", "steaming")),
        
        // Activities
        EmojiData("⚽", listOf("soccer", "football", "sport"), listOf("excited", "energetic"), listOf("game", "sport", "match"), "Soccer ball",
            listOf("white", "black", "hexagon", "pattern", "white and black", "checkered")),
        EmojiData("🎮", listOf("game", "gaming", "video game"), listOf("excited", "focused"), listOf("entertainment", "leisure"), "Video game",
            listOf("gray", "black", "buttons", "controller", "gamepad")),
        EmojiData("🎵", listOf("music", "song", "note"), listOf("happy", "relaxed"), listOf("entertainment", "party"), "Musical note",
            listOf("black", "note", "music", "staff", "musical")),
        EmojiData("📚", listOf("books", "study", "reading"), listOf("focused", "calm"), listOf("study", "education"), "Books",
            listOf("red", "blue", "green", "multiple", "stacked", "colored books")),
        EmojiData("✈️", listOf("airplane", "travel", "flight"), listOf("excited", "adventurous"), listOf("travel", "vacation"), "Airplane",
            listOf("white", "blue", "flying", "wings", "aircraft")),
        
        // Weather & Nature
        EmojiData("☀️", listOf("sun", "sunny", "weather"), listOf("happy", "bright"), listOf("summer", "good weather"), "Sun",
            listOf("yellow", "bright", "round", "rays", "yellow sun", "sunshine", "bright yellow")),
        EmojiData("🌧️", listOf("rain", "rainy", "weather"), listOf("calm", "melancholy"), listOf("bad weather", "indoor"), "Cloud with rain",
            listOf("gray", "blue", "cloud", "rain drops", "gray cloud", "blue rain")),
        EmojiData("❄️", listOf("snow", "snowflake", "winter"), listOf("calm", "peaceful"), listOf("winter", "cold"), "Snowflake",
            listOf("white", "blue", "crystal", "six points", "white snowflake", "ice")),
        EmojiData("🌈", listOf("rainbow", "colorful"), listOf("happy", "hopeful"), listOf("after rain", "beauty"), "Rainbow",
            listOf("red", "orange", "yellow", "green", "blue", "purple", "multicolor", "colorful", "all colors")),
        
        // Animals
        EmojiData("🐶", listOf("dog", "puppy", "pet"), listOf("happy", "loving"), listOf("pet", "companion"), "Dog face",
            listOf("brown", "tan", "dog", "floppy ears", "brown dog")),
        EmojiData("🐱", listOf("cat", "kitten", "pet"), listOf("cute", "playful"), listOf("pet", "companion"), "Cat face",
            listOf("orange", "yellow", "cat", "pointed ears", "orange cat")),
        EmojiData("🐼", listOf("panda", "cute"), listOf("cute", "peaceful"), listOf("wildlife", "nature"), "Panda face",
            listOf("black", "white", "panda", "black and white", "black eyes", "white face")),
        EmojiData("🦁", listOf("lion", "king", "wild"), listOf("proud", "strong"), listOf("wildlife", "nature"), "Lion face",
            listOf("yellow", "brown", "mane", "lion", "yellow mane", "brown face")),
        
        // Gestures
        EmojiData("👍", listOf("thumbs up", "good", "like"), listOf("approval", "satisfaction"), listOf("agreement", "approval"), "Thumbs up",
            listOf("skin tone", "thumb", "up", "hand", "pointing up")),
        EmojiData("👎", listOf("thumbs down", "bad", "dislike"), listOf("disapproval", "disappointment"), listOf("disagreement", "rejection"), "Thumbs down",
            listOf("skin tone", "thumb", "down", "hand", "pointing down")),
        EmojiData("👏", listOf("clap", "applause", "congratulations"), listOf("approval", "excitement"), listOf("celebration", "achievement"), "Clapping hands",
            listOf("skin tone", "two hands", "clapping", "applause")),
        EmojiData("🙏", listOf("pray", "please", "thanks"), listOf("grateful", "humble"), listOf("prayer", "gratitude"), "Folded hands",
            listOf("skin tone", "praying", "folded", "hands together")),
        EmojiData("✌️", listOf("peace", "victory", "two"), listOf("happy", "peaceful"), listOf("victory", "peace"), "Victory hand",
            listOf("skin tone", "two fingers", "peace sign", "v sign")),
        
        // Party & Celebration
        EmojiData("🎉", listOf("party", "celebration", "confetti"), listOf("excited", "joyful"), listOf("celebration", "party"), "Party popper",
            listOf("multicolor", "confetti", "streamers", "colorful", "party", "celebration")),
        EmojiData("🎊", listOf("celebration", "party", "confetti"), listOf("excited", "joyful"), listOf("celebration", "party"), "Confetti ball",
            listOf("multicolor", "confetti", "ball", "colorful", "party")),
        EmojiData("🎈", listOf("balloon", "party", "birthday"), listOf("happy", "excited"), listOf("birthday", "party"), "Balloon",
            listOf("red", "round", "balloon", "red balloon", "inflated")),
        EmojiData("🎁", listOf("gift", "present", "surprise"), listOf("happy", "excited"), listOf("birthday", "holiday"), "Wrapped gift",
            listOf("red", "ribbon", "bow", "box", "red gift", "wrapped", "red with bow")),
        
        // Work & Study
        EmojiData("💼", listOf("briefcase", "work", "business"), listOf("professional", "focused"), listOf("work", "office"), "Briefcase",
            listOf("brown", "black", "leather", "handle", "brown briefcase")),
        EmojiData("💻", listOf("laptop", "computer", "work"), listOf("focused", "productive"), listOf("work", "study"), "Laptop",
            listOf("gray", "silver", "screen", "keyboard", "gray laptop")),
        EmojiData("📝", listOf("memo", "note", "write"), listOf("focused", "organized"), listOf("work", "study"), "Memo",
            listOf("yellow", "paper", "pencil", "yellow paper", "note")),
        EmojiData("✅", listOf("check", "done", "complete"), listOf("satisfied", "accomplished"), listOf("completion", "success"), "Check mark button",
            listOf("green", "check", "mark", "green check", "checkmark")),
        
        // More emotions with visual features
        EmojiData("😌", listOf("relieved", "calm", "peaceful"), listOf("relieved", "calm", "peaceful"), listOf("relief", "peace"), "Relieved face",
            listOf("yellow face", "closed eyes", "peaceful", "calm", "relieved")),
        EmojiData("😋", listOf("yum", "delicious", "tasty"), listOf("satisfied", "happy"), listOf("food", "meal"), "Face savoring food",
            listOf("yellow face", "tongue", "licking", "enjoying", "savoring")),
        EmojiData("🤔", listOf("thinking", "ponder", "consider"), listOf("thoughtful", "curious"), listOf("question", "decision"), "Thinking face",
            listOf("yellow face", "hand on chin", "thinking", "pondering", "contemplating")),
        EmojiData("😇", listOf("angel", "innocent", "good"), listOf("innocent", "pure", "good"), listOf("innocence", "good deed"), "Smiling face with halo",
            listOf("yellow face", "halo", "golden", "angel", "halo above")),
        EmojiData("🤗", listOf("hug", "embrace", "comfort"), listOf("caring", "loving", "comforting"), listOf("support", "comfort"), "Hugging face",
            listOf("yellow face", "open arms", "hugging", "embracing", "arms wide")),
        EmojiData("😘", listOf("kiss", "love", "affection"), listOf("loving", "affectionate"), listOf("romance", "affection"), "Face blowing a kiss",
            listOf("yellow face", "kiss", "heart", "blowing kiss", "kiss mark")),
        EmojiData("😉", listOf("wink", "playful", "teasing"), listOf("playful", "teasing", "friendly"), listOf("joke", "flirtation"), "Winking face",
            listOf("yellow face", "wink", "one eye closed", "playful", "teasing")),
        EmojiData("🙄", listOf("eye roll", "sarcastic", "annoyed"), listOf("annoyed", "sarcastic", "frustrated"), listOf("disagreement", "sarcasm"), "Face with rolling eyes",
            listOf("yellow face", "rolling eyes", "sarcastic", "annoyed", "eyes up")),
        EmojiData("🤤", listOf("drooling", "hungry", "desire"), listOf("hungry", "desiring", "craving"), listOf("food", "desire"), "Drooling face",
            listOf("yellow face", "drool", "drooling", "water", "desiring")),
        EmojiData("😷", listOf("mask", "sick", "ill"), listOf("sick", "unwell", "careful"), listOf("illness", "health"), "Face with medical mask",
            listOf("yellow face", "white mask", "medical", "blue mask", "face mask")),
        EmojiData("🤒", listOf("sick", "fever", "ill"), listOf("sick", "unwell", "tired"), listOf("illness", "health"), "Face with thermometer",
            listOf("yellow face", "thermometer", "red", "fever", "sick", "red thermometer")),
        EmojiData("🤕", listOf("injured", "hurt", "bandage"), listOf("hurt", "injured", "pain"), listOf("injury", "accident"), "Face with head-bandage",
            listOf("yellow face", "white bandage", "bandage", "injured", "white wrap")),
        EmojiData("🤧", listOf("sneeze", "sick", "cold"), listOf("sick", "unwell"), listOf("illness", "cold"), "Sneezing face",
            listOf("yellow face", "sneezing", "tissue", "sick", "achoo")),
        EmojiData("🥵", listOf("hot", "sweating", "fever"), listOf("hot", "uncomfortable", "feverish"), listOf("heat", "fever"), "Hot face",
            listOf("red face", "sweating", "red color", "hot", "red hot", "sweat drops", "red sweating")),
        EmojiData("🥶", listOf("cold", "freezing", "shivering"), listOf("cold", "freezing", "uncomfortable"), listOf("cold weather", "winter"), "Cold face",
            listOf("blue face", "cold", "blue color", "freezing", "blue cold", "ice", "blue freezing")),
        EmojiData("😵", listOf("dizzy", "confused", "woozy"), listOf("confused", "dizzy", "disoriented"), listOf("confusion", "illness"), "Dizzy face",
            listOf("yellow face", "dizzy", "spirals", "confused", "spinning")),
        EmojiData("🤯", listOf("exploding head", "mind blown", "shocked"), listOf("shocked", "amazed", "overwhelmed"), listOf("surprise", "amazement"), "Exploding head",
            listOf("yellow face", "exploding", "brain", "mind blown", "shocked")),
        EmojiData("🤠", listOf("cowboy", "western", "hat"), listOf("confident", "adventurous"), listOf("western", "adventure"), "Cowboy hat face",
            listOf("yellow face", "brown hat", "cowboy hat", "western", "brown cowboy hat")),
        EmojiData("🥳", listOf("party", "celebration", "birthday"), listOf("excited", "joyful", "celebratory"), listOf("birthday", "celebration"), "Partying face",
            listOf("yellow face", "party hat", "confetti", "celebration", "colorful hat")),
        EmojiData("🤓", listOf("nerd", "geek", "smart"), listOf("intelligent", "focused", "studious"), listOf("study", "intelligence"), "Nerd face",
            listOf("yellow face", "glasses", "big glasses", "nerdy", "thick glasses")),
        EmojiData("🧐", listOf("monocle", "investigating", "curious"), listOf("curious", "investigative", "thoughtful"), listOf("investigation", "curiosity"), "Face with monocle",
            listOf("yellow face", "monocle", "glass", "investigating", "single glass")),
        

    )
    

    fun getAllSearchableText(): String {
        return emojis.joinToString(" ") { it.getAllSearchableText() }
    }
}
